"""init

Revision ID: a57573fa31f4
Revises: 
Create Date: 2026-04-10 17:26:53.531763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a57573fa31f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    op.drop_table('filmes')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=2, scale=1),
               existing_nullable=True)

    op.create_table('filmes',
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genero', mysql.CHAR(length=50), nullable=False),
    sa.Column('duracao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_item'], ['itens.id_item'], name=op.f('filmes_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_item'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('livros',
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paginas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_item'], ['itens.id_item'], name=op.f('livros_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_item'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
